import './globals.css'
import { Inter } from 'next/font/google'
import HeaderComp from '../components/Header.comp'
import FooterComp from '../components/Footer.comp'
import { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComp />
        <main className="container">{children}</main>
        <FooterComp />
      </body>
    </html>
  )
}
